config/routes.rb
Rails.application.routes.draw do
  get 'cart_items/create'
  get 'cart_items/update'
  get 'cart_items/destroy'
  get 'orders/create'
  get 'products/index'
  get 'products/show'
  get 'products/new'
  get 'products/create'
  get 'products/edit'
  get 'products/update'
  get 'products/destroy'
  root 'products#index'
  resources :registrations
  resources :sessions, only: [:new, :create]
  resources :posts do
    resources :comments do
      get '/add', to: 'comments#new', as: :add_child_comment
      post '/', to: 'comments#create', as: :add_child_comment_parent
    end
  end
  resources :comments
  resources :users
  resources :products
  resources :buyers
  resources :sellers
  resources :cart
  resources :cart_items
  delete 'logout' => 'sessions#destroy', as: :logout
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  belongs_to :parent_comment, class_name: 'Comment', optional: true
  has_many :children, class_name: 'Comment', foreign_key: :parent_comment_id, dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]
  before_action :set_post, only: %i[ create ]
  before_action :set_parent, only: %i[ create ]
  before_action :require_login
  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
    @show_comments = true
    @post = Post.find(params[:post_id])
    if params[:comment_id]
      @parent_comment = Comment.find(params[:comment_id])
      @comment.parent_comment = @parent_comment
    end
  end
  
  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.post = Post.find(params[:post_id])
    @comment.user = User.find(current_user.id)
    if params[:comment_id]
      @parent_comment = Comment.find(params[:comment_id])
      @comment.parent_comment = @parent_comment
    end
    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(@post), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy!

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def set_post
      @post = Post.find(params[:post_id])
    end

    def set_parent
      if params[:comment_id]
        @parent_comment = Comment.find(params[:comment_id])
      end
    end
    

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:content, :post_id, :user_id, :parent_comment_id)
    end

    private
    
    def require_login
      unless logged_in?
        redirect_to new_session_path, alert: "You must be logged in to access this page."
      end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
    def recursive_comments(comments, post, valid = false)
      html = ''
      comments.each do |comment|
        if valid || comment.parent_comment_id.nil?
          html += render(partial: 'comments/comment', locals: { comment: comment, post: post, green: false })
        end
      end
      html.html_safe
    end
  end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
<% if green  %>
<div class="card bg-success" style="--bs-bg-opacity: .5;">
<% else  %>
<div class="card">
<% end %>
    <h5 class="card-header"><i class="bi bi-person-circle"></i>&nbsp;<%= User.find(comment.user_id).username %><span class="text-muted" style="--bs-text-opacity: .5;">&nbsp;•&nbsp;<%= time_ago_in_words(Comment.find(comment.id).created_at).gsub('about ', '') %> ago</span></h5>
    <div class="card-body">
      <p class="card-text"><%= comment.content %></p>
        <%= link_to post_comment_add_child_comment_path(post_id: comment.post_id, comment_id: comment.id), class: "btn btn-outline-primary" do %>
          <i class="bi bi-chat-dots"></i>
        <% end %>
      <%= recursive_comments(comment.children, comment.post_id, true) if comment.children.any? %>
    </div>
  </div>
  
</div>

app/views/comments/_form.html.erb
<% url = @parent_comment.present? ? post_comment_add_child_comment_parent_path(post_id: @post.id, parent_id: @parent_comment.id) : post_comments_path(@post) %>
<% comment = @parent_comment.present? ? @parent_comment.children.build : @post.comments.build %>

<%= form_with(model: [comment.new_record? ? @post : @parent_comment, comment], url: url) do |form| %>

<% if @comment.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
    <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="card">
    <h5 class="card-header"><i class="bi bi-person-circle"></i>&nbsp;You</h5>
    <div class="card-body">
      <p class="card-text">
        <div class="input-group mb-3">
          <span class="input-group-text" id="basic-addon1">Content</span>
          <%= form.text_area :content, class:"form-control" %>
        </div>  
      </p>
      <div>
        <%= form.submit "Send", class: "btn btn-success" %>
      </div>
    </div>
  </div>

<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<div class="container">
  <p></p>
<h1>New comment</h1>
<div>
  <%= link_to "Back to posts", posts_path, class:"btn btn-primary" %>
</div>
<%= render partial: 'posts/post', locals: { post: @post, show_comments: true, parent_comment: @parent_comment } %>
<%= render 'form', comment: @comment, post: @post, parent_comment: @comment.parent_comment %>

<br>

</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>