config/routes.rb
Rails.application.routes.draw do
  get 'cart_items/create'
  get 'cart_items/update'
  get 'cart_items/destroy'
  get 'orders/create'
  get 'products/index'
  get 'products/show'
  get 'products/new'
  get 'products/create'
  get 'products/edit'
  get 'products/update'
  get 'products/destroy'
  root 'products#index'
  resources :registrations
  resources :sessions, only: [:new, :create]
  resources :posts do
    resources :comments do
      get '/add', to: 'comments#new', as: :add_child_comment
      post '/', to: 'comments#create', as: :add_child_comment_parent
    end
  end
  resources :comments
  resources :users
  resources :products
  resources :buyers
  resources :sellers
  resources :cart
  resources :cart_items
  delete 'logout' => 'sessions#destroy', as: :logout
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/buyer.rb
class Buyer < ApplicationRecord
  belongs_to :user
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :buyer
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  belongs_to :parent_comment, class_name: 'Comment', optional: true
  has_many :children, class_name: 'Comment', foreign_key: :parent_comment_id, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :buyer
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :seller
end

app/models/seller.rb
class Seller < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, presence: true, uniqueness: true
    validates :username, presence: true, uniqueness: true
    validates :name, presence: true
    validates :password, presence: true, confirmation: true, length: { minimum: 6 }
    has_one :buyer
    has_one :seller
    has_many :transactions, through: :buyer
    has_one :cart
  end
  

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all
    @users = User.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include CommentsHelper
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :require_login

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.upvotes = 0
    @post.downvotes = 0
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
  


  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :upvotes, :downvotes, :user_id)
    end

    private

    def require_login
      unless logged_in?
        redirect_to new_session_path, alert: "You must be logged in to access this page."
      end
    end
end

app/controllers/users_controller.rb
  class UsersController < ApplicationController
    before_action :set_user, only: %i[ show edit update destroy ]
    before_action :authenticate_user!, only: [:new, :create]
    before_action :correct_user, only: [:edit, :update]

    # GET /users or /users.json
    def index
      @users = User.all
    end

    # GET /users/1 or /users/1.json
    def show
      @user = User.find_by(id: params[:id])
      unless @user
        flash[:alert] = "User not found"
        redirect_to users_path
      end
    end

    # GET /users/new
    def new
      redirect_to new_session_path
    end

    # GET /users/1/edit
    def edit
    end

    # POST /users or /users.json
    def create
      @user = User.new(user_params)
    
      respond_to do |format|
        if @user.save
          format.html { redirect_to root_path, notice: "Inscription réussie !" }
          format.json { render :show, status: :created, location: @user }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end    

    # PATCH/PUT /users/1 or /users/1.json
    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /users/1 or /users/1.json
    def destroy
      @user.destroy!

      respond_to do |format|
        format.html { redirect_to users_url, notice: "User was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_user
        @user = User.find(params[:id])
      end

      # Vérifie que l'utilisateur actuellement connecté est le même que celui dans l'URL
      def correct_user
        @user = User.find(params[:id])
        redirect_to(root_url) unless current_user == @user
      end

      # Only allow a list of trusted parameters through.
      def user_params
        params.require(:user).permit(:username, :name, :password, :email, :seller)
      end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
    def recursive_comments(comments, post, valid = false)
      html = ''
      comments.each do |comment|
        if valid || comment.parent_comment_id.nil?
          html += render(partial: 'comments/comment', locals: { comment: comment, post: post, green: false })
        end
      end
      html.html_safe
    end
  end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="card">
    <h5 class="card-header"><i class="bi bi-person-circle"></i>&nbsp;You</h5>
    <div class="card-body">
      <h5 class="card-title">
        <div class="input-group mb-3">
          <span class="input-group-text" id="basic-addon1">Title</span>
          <%= form.text_field :title, class: "form-control", placeholder: "Enter title" %>
        </div>
      </h5>
      <p class="card-text">
        <div class="input-group mb-3">
          <span class="input-group-text" id="basic-addon1">Content</span>
          <%= form.text_area :content, class:"form-control" %>
        </div>  
      </p>
      <div>
        <%= form.submit(post.persisted? ? "Update Post" : "Create Post", class: "btn btn-success") %>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="card" id="<%= dom_id post %>">
  <h5 class="card-header"><i class="bi bi-person-circle"></i>&nbsp;<%= User.find(post.user_id).username %><span class="text-muted" style="--bs-text-opacity: .5;">&nbsp;•&nbsp;<%= time_ago_in_words(Post.find(post.id).created_at).gsub('about ', '') %> ago</span></h5>
  <div class="card-body">
    <h5 class="card-title"><%= post.title %></h5>
    <p class="card-text"><%= post.content %></p>
    <% if !@show_comments %>
      <%= link_to post, class: "btn btn-outline-primary" do %>
        <i class="bi bi-eye-fill"></i>
      <% end %>
      <%= link_to new_post_comment_path(post), class: "btn btn-outline-primary" do %>
        <i class="bi bi-chat-dots"></i>
      <% end %>
    <% end %>
    <div class="btn-group" role="group" aria-label="Basic outlined example">
      <button type="button" class="btn btn-outline-success">
        <i class="bi bi-caret-up-square"></i>
        <%= post.upvotes %></button>
      <button type="button" class="btn btn-outline-danger">
        <i class="bi bi-caret-down-square"></i>
        <%= post.downvotes %></button>
    </div>
  </div>
  <div class="container">
  <% if !@show_comments %>
    <%= recursive_comments(post.comments, @post) %>
  <% end %>
  <% if @parent_comment %>
    <%= render partial: 'comments/comment', locals: {comment: @parent_comment, green: true} %>
  <% end %>
</div>
</div>

app/views/posts/edit.html.erb
<p></p>
<div class="container">
<h1>Editing post</h1>
<div>
  <%= link_to "Back to posts", posts_path, class:"btn btn-primary" %>
</div>
<%= render "form", post: @post %>
</div>

app/views/posts/index.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <h1>Latest posts</h1>
  <% if current_user %> <!-- Vérifie si un utilisateur est connecté -->
    <%= link_to "New post", new_post_path, class: "btn btn-primary" %>
  <% end %>
  <div id="posts">
    <% @posts.each do |post| %>
      <%= render post %>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <p></p>
<h1>New post</h1>
<div>
  <%= link_to "Back to posts", posts_path, class:"btn btn-primary" %>
</div>
<%= render "form", post: @post %>

</div>

app/views/posts/show.html.erb
<div class="container">
<p style="color: green"><%= notice %></p>
<h1>More details</h1>
<%= link_to "Back to posts", posts_path, class: "btn btn-primary" %>
<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post), class: "btn btn-primary" %>
  <%= button_to "Destroy this post", @post, method: :delete, class: "btn btn-danger" %>
</div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="card">
    <div class="card-body">
      <p class="card-text">
        <div class="input-group mb-3">
          <span class="input-group-text" id="basic-addon1">Username</span>
          <%= form.text_field :username, class: "form-control", placeholder: "chucknorris" %>
        </div>
        <div class="input-group mb-3">
          <span class="input-group-text" id="basic-addon1">Name</span>
          <%= form.text_field :name, class: "form-control", placeholder: "Chuck Norris" %>
        </div>
        <div class="input-group mb-3">
          <span class="input-group-text" id="basic-addon1">Email</span>
          <%= form.email_field :email, class: "form-control", placeholder: "user@example.com" %>
        </div>
        <div class="input-group mb-3">
          <span class="input-group-text" id="basic-addon1">Password</span>
          <%= form.password_field :password, class: "form-control", placeholder: "**********" %>
        </div>
      </p>
      <p>
      <div class="d-flex justify-content-center align-items-center">
        <%= form.submit(user.persisted? ? "Update" : "Create", class: "btn btn-success") %>
      </div>
      </p>
    </div>
  </div>
  </div>
  </div>
<% end %>

app/views/users/_user.html.erb
<div class="card" id="<%= dom_id user %>">
  <h5 class="card-header">
    <i class="bi bi-person-circle"></i>&nbsp;
    <%= user.username %>
    
    <div class="btn-group position-absolute end-0 translate-middle " role="group" aria-label="Basic outlined example">
      <%= link_to user, class: "btn btn-outline-primary btn-sm" do %>
        <i class="bi bi-eye-fill"></i>
      <% end %>
      <% if current_user == user %>
        <%= link_to edit_user_path(user), class: "btn btn-outline-primary btn-sm" do %>
          <i class="bi bi-pencil"></i>
        <% end %>
      <% end %>
    </div>
  </h5>
  <div class="card-body">
    <p class="card-text">Name : <%= user.name %></p>
    <p class="card-text">Email : <%= user.email %></p>
    <p class="card-text"><%= user.password %></p>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <p></p>
<h1>Editing user</h1>
<div>
  <%= link_to "Back to users", users_path, class:"btn btn-primary" %>
</div>
<%= render "form", user: @user %>
</div>

app/views/users/index.html.erb
<div class="container">
<p style="color: green"><%= notice %></p>

<h1>Users</h1>
<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
  <% end %>
</div>


</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>
  <h1>More details</h1>
  <%= link_to "Back to users", users_path, class: "btn btn-primary" %>
  <%= render @user %>

  <div>
  </div>
</div>