config/routes.rb
Rails.application.routes.draw do
  get 'cart_items/create'
  get 'cart_items/update'
  get 'cart_items/destroy'
  get 'orders/create'
  get 'products/index'
  get 'products/show'
  get 'products/new'
  get 'products/create'
  get 'products/edit'
  get 'products/update'
  get 'products/destroy'
  root 'products#index'
  resources :registrations
  resources :sessions, only: [:new, :create]
  resources :posts do
    resources :comments do
      get '/add', to: 'comments#new', as: :add_child_comment
      post '/', to: 'comments#create', as: :add_child_comment_parent
    end
  end
  resources :comments
  resources :users
  resources :products
  resources :buyers
  resources :sellers
  resources :cart
  resources :cart_items
  delete 'logout' => 'sessions#destroy', as: :logout
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/buyer.rb
class Buyer < ApplicationRecord
  belongs_to :user
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :buyer
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  belongs_to :parent_comment, class_name: 'Comment', optional: true
  has_many :children, class_name: 'Comment', foreign_key: :parent_comment_id, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :buyer
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :seller
end

app/models/seller.rb
class Seller < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, presence: true, uniqueness: true
    validates :username, presence: true, uniqueness: true
    validates :name, presence: true
    validates :password, presence: true, confirmation: true, length: { minimum: 6 }
    has_one :buyer
    has_one :seller
    has_many :transactions, through: :buyer
    has_one :cart
  end
  

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
    def recursive_comments(comments, post, valid = false)
      html = ''
      comments.each do |comment|
        if valid || comment.parent_comment_id.nil?
          html += render(partial: 'comments/comment', locals: { comment: comment, post: post, green: false })
        end
      end
      html.html_safe
    end
  end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railskuten</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link href="https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-app" tabindex="-1">
      <div class="container-fluid">
        <a class="navbar-brand text-white m-plus" href="/products">
          <%= image_tag 'logo.png', alt: 'Logo', width: '30', height: '30', class: 'd-inline-block align-text-top' %>
          ailskuten
        </a>
        <div class="collapse navbar-collapse ">
          <ul class="navbar-nav">

          </ul>
        <div class="position-absolute end-0 translate-middle-connect" role="search">
            <% if logged_in? %>
              <%= button_to "Déconnexion", logout_path, method: :delete, class: "btn btn-outline-light" %>
              <% else %>
              <%= link_to "Connexion", new_session_path, class: "btn btn-primary btn-sm" %>
            <% end %>
        </div>
      </div>
    </nav>

    <%= yield %>
    <%= notice %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>